CREATE DATABASE cbir;
CREATE TABLE keyword(
id INT PRIMARY KEY ,
VALUE VARCHAR(200) UNIQUE
);

CREATE TABLE picture(
id INT PRIMARY KEY,
NAME VARCHAR(200),
keywd VARCHAR(200),
FOREIGN KEY (keywd) REFERENCES keyword(VALUE)
);

DROP TABLE keyword;

CREATE TABLE indexlocation(
id INT PRIMARY KEY,
VALUE VARCHAR(100)
);



SELECT * FROM keyword;

CREATE TABLE ipinfo(
ipaddress VARCHAR(20) PRIMARY KEY,
PORT VARCHAR(10)
);

INSERT INTO ipinfo() VALUES('12','123');